---
title: "Project"
date: "Fall 2018"
output: 
  html_document:
   toc: true
   toc_depth: 3
   toc_float: true 
   theme: flatly
---

<!-- R setup -->
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
library(tidyverse)

```

<!-- Data  -->
<!-- Internet -->
```{r, echo=FALSE, message=FALSE, warning=FALSE}
internetusers_cia2017 <- read_csv("Data/internetusers_cia2017.csv")
internetusers_cia2017 %>% head()
```
<!-- Population -->
```{r, echo=FALSE, message=FALSE, warning=FALSE}
population_cia2017 <- read_csv("Data/population_cia2017.csv")
population_cia2017 %>% head()
```
<!-- Region -->
```{r, echo=FALSE, message=FALSE, warning=FALSE}
world_regions <- read_csv("Data/world_regions.csv")
world_regions %>% head()
```
<!-- Democracy -->
```{r, echo=FALSE, message=FALSE, warning=FALSE}
democracyindex2017 <- read_csv("Data/democracyindex2017.csv")
democracyindex2017 %>% head()
```
<!-- Education -->
```{r, echo=FALSE, message=FALSE, warning=FALSE}
education_cia2017 <- read_csv("Data/education_cia2017.csv")
education_cia2017 %>% head()
```
<!-- Economy -->
```{r, echo=FALSE, message=FALSE, warning=FALSE}
gdpppp_cia2017 <- read_csv("Data/gdpppp_cia2017.csv")
gdpppp_cia2017 %>% head()
```
<!-- Health -->
```{r, echo=FALSE, message=FALSE, warning=FALSE}
lifeexpect_cia2017 <- read_csv("Data/lifeexpect_cia2017.csv")
lifeexpect_cia2017 %>% head()
```
```{r, echo=FALSE, message=FALSE, warning=FALSE}
healthexpend_cia2017 <- read_csv("Data/healthexpend_cia2017.csv")
healthexpend_cia2017 %>% head()
```


## Fancy Map
```{r}
library(maps)

world <- map_data("world") 

internetusers_cia2017 <- read_csv("Data/internetusers_cia2017.csv")

iu <- internetusers_cia2017 %>% rename(region = Country) 

iu$region[4] <- "USA" # to match world map data

iu <- semi_join(iu, world, by = "region") #only keep countries according to world map data

# code below is modified from 
# https://stackoverflow.com/questions/29614972/ggplot-us-state-map-colors-are-fine-polygons-jagged-r
gg <- ggplot()

gg <- gg + geom_map(
  data = world,
  map = world,
  aes(x = long, y = lat, map_id = region),
  fill = "#ffffff",
  color = "#ffffff",
  size = 0.20
  )
  
  gg <- gg + geom_map(
  data = iu,
  map = world,
  aes(fill = `INTERNET USERS`, map_id = region),
  color = "#ffffff",
  size = 0.15
  )
  
  gg <- gg + scale_fill_continuous(low = 'thistle2', high = 'darkblue',
  guide = 'colorbar')
  gg
```


